name: Run AI News Tracker

on:
  schedule:
    - cron: '0 */3 * * *'  # 🔁 Runs every 3 hours
  workflow_dispatch:       # ▶️ Allows manual run from GitHub UI

jobs:
  track-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install openai gspread oauth2client

      - name: Run script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: python main.py
