name: Scrape Articles Daily
on:
  schedule:
    - cron: '0 12 * * *'  # Runs at 12 PM UTC daily
  workflow_dispatch:  # Enable manual runs

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run scraper
        run: python scrape.py
      - name: Upload results
        uses: actions/upload-artifact@v4  # Critical fix
        with:
          name: articles
          path: articles.csv
