name: Daily Article Scraper
on:
  schedule:
    - cron: '0 8 * * *'  # Run at 8 AM UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run today's scraper
        run: python scrape.py
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: todays-articles
          path: articles.csv
