name: Daily Article Scraper
on:
  schedule:
    - cron: '0 8 * * *'  # Runs at 8 AM UTC daily
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run Scraper
        run: python scrape_articles.py
        
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: todays-articles
          path: "Today's Articles.xlsx"
