name: Test Responses API

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12  # ✅ Valid version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run OpenAI Responses API test
        run: python test_response.py
